name: Deploy React Frontend to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        working-directory: "hostel-leave-system - Copy/frontend"
        run: npm install

      - name: Build React app
        working-directory: "hostel-leave-system - Copy/frontend"
        run: npm run build
        env:
          PUBLIC_URL: /Hostel_Leave_Application_System

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "hostel-leave-system - Copy/frontend/build"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
